### ISSUE TITLE
Hides when selecting another app

### ISSUE THREAD

**Issue by iamhenry** [romannurik/Sketch-Stickers#8] opened 2018-07-05 21:11 UTC
When I try to exit Stickers it hides itself when I select another app that isn't Sketch. It hides abruptly as if Sketch crashed but if I go to Window -> "Sketch Document" then the Sketch file presents itself again.
![stickers](https://user-images.githubusercontent.com/923439/42348184-56a66634-805d-11e8-9d50-179f289ccb54.gif)

**Comment by romannurik** [comment] 2018-07-05 21:16
Hmm. Stickers intentionally closes it's own window if you click outside it but I'm not sure the clicking outside hiding Sketch is intended. Will look into it!

**Comment by romannurik** [comment] 2018-07-17 02:56
Just reproduced it... very weird! Thanks for filing.

**Comment by romannurik** [comment] 2018-07-17 03:03
This will be fixed in a future release... needed this line of code for any developers that stumble across this:

`this.browserWindow._panel.setHidesOnDeactivate(false);`

(since `NSPanel` by default hides itself when deactivated)

**Closed by romannurik** 2018-07-17 03:03 UTC
