### ISSUE TITLE
Symbols not imported correctly when dragging+dropping stickers

### ISSUE THREAD

**Issue by konorul** [romannurik/Sketch-Stickers#2] opened 2018-05-07 13:39 UTC
We have sketch library on dropbox. I added sticker metadata and sticker artboard and everything worked for me. But when other designers try to insert symbols with your plugin they get missing symbols.

**Comment by konorul** [comment] 2018-05-07 13:55
Simple objects that is not symbols can be pasted without a problem.

**Comment by romannurik** [comment] 2018-05-07 14:13
Right now this is intentional, you need to manually create an example instance of each symbol you want listed in Stickers. I'm exploring ways to allow Stickers to automatically index symbols (and put them in the right categories/sections), feedback and ideas there are welcome :)

**Comment by konorul** [comment] 2018-05-08 07:58
You mean I need to create separate page and artboard on it where I put instances of symbols I need? But I did it that way and no one except me can paste stickers as a symbol. They all get object with red stripes which says "Missing Symbol". But in plugin they see everything correctly.

**Comment by konorul** [comment] 2018-05-08 12:08
Don't know why but duplicating the file with different name and removing original, relocating library on each computer solved the problem. Sent you video on roman@nurik.net.

**Comment by konorul** [comment] 2018-05-08 12:13
But we also have another problem. Some kind of a ghost sticker duplicates. Video in attachment
[duplicates.zip](https://github.com/romannurik/Sketch-Stickers/files/1983791/duplicates.zip)
.

**Comment by romannurik** [comment] 2018-05-08 15:27
Re: the original issue, I'm not sure what caused that... could be something to do with caching? If this keeps coming up please try to share as much about the situation as you can! Also another thing to try is to delete `~/Library/Caches/net.nurik.roman.sketch.stickers` (that's where the index is kept).

Re: the duplicates... these could be showing up if you have multiple libraries installed with the same sticker sections. Right now the plugin doesn't differentiate stickers between libraries you have installed. Is that the case for you?

**Comment by konorul** [comment] 2018-05-08 15:37
Re: the duplicates... 

No, duplicates all from the same library. When I delete section from metadata stickers and duplicates disappear. And duplicates don't have a preview.

**Comment by konorul** [comment] 2018-05-08 15:51
Very strange, duplicates disappear when I delete section from metadata but they still visible when I completely delete library from sketch. Cash folder is in attachment.
[net.nurik.roman.sketch.stickers.zip](https://github.com/romannurik/Sketch-Stickers/files/1984672/net.nurik.roman.sketch.stickers.zip)

**Comment by romannurik** [comment] 2018-05-08 21:07
OK it looks like both the issues you're having are related to the cache going out of sync w/ the library. Not sure what could be causing this state, but I'll keep digging. The way the plugin checks for whether the cache is out of date is using the library file's system "modified date" so if for example the library was being changed but its modified date wasn't being updated, the cache would definitely go out of sync..

**Comment by konorul** [comment] 2018-05-09 09:26
One more thing. I added more stickers and they all get duplicates.

By the way, you making very useful plugin, please don't stop working on it)

**Comment by richardsison** [comment] 2018-06-05 02:52
Not sure if this is the same issue, but I'm also having issues placing Stickers from my Library.

It's weird. The Library Symbol seems to be making the connection correctly (and is previewing in the Inspector). But it appears broken on the artboard itself.

![image](https://user-images.githubusercontent.com/587608/40952377-6262a228-68be-11e8-9646-d7c6e67c738e.png)

Clicking on the Inspector and re-selecting the symbol fixes it. But this is a tedious process. Especially when I need to import a lot.

Here's an example of how I fix it manually: https://d.pr/i/RSTpyt

**Comment by romannurik** [comment] 2018-06-05 03:38
@richardsison would you be comfortable sharing your library Sketch file for troubleshooting? (privately if you'd like)

**Comment by richardsison** [comment] 2018-06-05 04:04
Yeah I can share small demo file if you like? Send here? roman@nurik.net

**Comment by romannurik** [comment] 2018-06-05 04:08
That'd be great! I'll take a look asap

**Comment by romannurik** [comment] 2018-06-08 04:06
@richardsison Thanks for the test file, I reproduced the problem you're having! I'll be looking into fixing this ASAP, haven't started digging into the cause yet. I also suspect this is a different issue from the original poster, but don't know that it's worth filing a separate bug unless the fix takes several iterations.

**Comment by romannurik** [comment] 2018-06-08 05:42
@richardsison Found the problem and the fix is commited to the repo (change 160f5179f337aaa11c7f86c64dfdf3908bea98e7). I haven't pushed an update to the plugin yet, hoping to do that in the next few days.

**Comment by richardsison** [comment] 2018-06-11 23:09
Woo hoo! Legend! I'll check it out today.

**Comment by richardsison** [comment] 2018-06-11 23:42
Weird, it doesn't work for me at all now. I've reinstalled it and everything but no luck.

It when I select "Show Stickers" on the same file, it just says "[Indexing Libraries](https://d.pr/i/sXJXPA)" but doesn't actually do anything.

**Comment by romannurik** [comment] 2018-06-11 23:56
Hey Richard I think there's still a bug where plugin updates aren't being handled correctly. Have you tried restarting Sketch?

**Comment by romannurik** [comment] 2018-08-07 21:03
PSA: v0.2.3 fixes issue #11 which is similar to some of the things in this thread.

**Comment by romannurik** [comment] 2019-02-27 02:11
Going to close this out... I've made some very recent changes to how symbol importing works.

**Closed by romannurik** 2019-02-27 02:11 UTC
Labels: bug
